name: Periodic health check

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-1e8w.onrender.com/health
          max-attempts: 3
          retry-delay: 5s
